version: "3.8"

services:
  app:
    build: .
    container_name: salesyodha_app
    restart: always
    ports:
      - "8080:8080"

    #  Explicit env load (double safety)
    env_file:
      - .env

    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/salesyodha_production
      SPRING_DATASOURCE_USERNAME: prod_user

      #  HARD FIX (no more crash)
      SPRING_DATASOURCE_PASSWORD: Yoddha@2026#

      SPRING_PROFILES_ACTIVE: prod

    depends_on:
      - db

    volumes:
        - ./uploads:/app/uploads

  db:
    image: mariadb:10.6
    container_name: salesyodha_db
    restart: always

    env_file:
      - .env

    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: salesyodha_production
      MYSQL_USER: prod_user
      MYSQL_PASSWORD: Yoddha@2026#

    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: